name: Build to fly.io

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    name: Setup and Build to fly.io
    env:
      FLY_ACCESS_TOKEN: ${{secrets.FLY_TOKEN}}
    steps:
      - name: install fly cli
        uses: actions/checkout@v3
      - run: sh <(curl -s https://fly.io/install.sh)
      - run: /home/runner/.fly/bin/flyctl version
      - run: /home/runner/.fly/bin/flyctl auth docker
      - run: /home/runner/.fly/bin/flyctl deploy



